### ISSUE TITLE
Feature: Add IPv6 support

### ISSUE THREAD

**Issue by olljanat** [olljanat/docker-bgp-lb#1]
Linking to https://github.com/docker/docs/issues/19556 support for IPv4+IPv6 dual stack first and maybe also IPv6 only (need update to Docker side too, look: https://github.com/olljanat/moby/commit/4534a75abde0bceb19110b643b2412310aa694c5 ) would be nice.

Currently code already have parts of IPv6 but it is completely untested.

It would also help if someone know Cloud platform which provided cheap IPv6 only test environments.

**Comment by daryll-swer** [comment]
> It would also help if someone know Cloud platform which provided cheap IPv6 only test environments.

Use Akamai Linode VM, as they are the only “cheap” option that supports native IPv6 with a routed /64 to the VM (Docker host). You can test it there without any NAT66/NDP Proxying crap.

**Comment by olljanat** [comment]
IPv6 support added and IPv6 addresses included to all examples in readme. Works with and without Swarm mode.
It looks to be that in Swarm mode DNS will always return IPv4 addresses which looks to be known issue https://github.com/moby/moby/issues/42712
On standalone mode connectivity works even with names because those containers have static IPs and DNS records are added with `--add-host` parameter in those examples.

However, looks that Linode does not like my signup request and local ISP does not offer IPv6 so cannot test it with public addresses at the moment.

Looked also IPv6 mode a bit more but it looks to be that at least https://github.com/moby/moby/pull/43033 needs to be solved first as there is some nasty logic inside of Docker which expects IPv4 addresses always be available.

**Comment by daryll-swer** [comment]
> However, looks that Linode does not like my signup request and local ISP does not offer IPv6 so cannot test it with public addresses at the moment.

I think you should apply for your own /32 or /48 from the RIR in your region, and get an ASN. This way you can play with it on Vultr with free BGP IP Transit.
